# Generated by Django 2.2 on 2019-04-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('post_content', models.CharField(max_length=512)),
                ('liked_by', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
