# Generated by Django 2.2 on 2019-04-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_UID',
            fields=[
                ('unique_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('unique_id', models.CharField(max_length=3, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('followers', models.CharField(max_length=2000, null=True)),
                ('following', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
